// import { Inter } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import "./globals.css";
import { db } from "@/lib/db";
import { auth } from "@clerk/nextjs/server";
import Link from "next/link";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const { userId } = auth();

  const result = await db.query(
    `SELECT * FROM profiles WHERE clerk_id = '${userId}'`
  );
  console.log(result);

  if (result.rowCount === 0 && userId) {
    await db.query(`INSERT INTO profiles (clerk_id) VALUES ('${userId}')`);
  }
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <header>
            <nav>
              <Link href="/">Home</Link>
              <Link href="/posts">Posts</Link>
              {result.rows.map((profile) => (
                <div key={profile.id}>
                  <Link href={`/user/${profile.id}`} key={profile.id}>
                    My Profile
                  </Link>
                </div>
              ))}
            </nav>
            <SignedOut>
              <SignInButton />
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header>
          <main>{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
