import { Itim } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import "./globals.css";
import { db } from "@/lib/db";
import { auth } from "@clerk/nextjs/server";
import Link from "next/link";
import ProfileForm from "./components/ProfileForm";

const itim = Itim({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const { userId } = auth();

  const result = await db.query(
    `SELECT * FROM profiles WHERE clerk_id = '${userId}'`
  );

  if (result.rowCount === 0 && userId) {
    await db.query(`INSERT INTO profiles (clerk_id) VALUES ('${userId}')`);
  }

  const hasUsername = result.rows[0]?.username !== null ? true : false;
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <div>
            <header>
              <nav>
                <Link href="/">Home</Link>
                <Link href="/about">About</Link>
                <Link href="/posts">Posts</Link>
                {result.rows.map((profile) => (
                  <div key={profile.id}>
                    <Link href={`/user/${profile.id}`} key={profile.id}>
                      My Profile
                    </Link>
                  </div>
                ))}
              </nav>
              <SignedOut>
                <SignInButton />
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </header>
            <main>
              <SignedOut>{children}</SignedOut>
              <SignedIn>
                {hasUsername && children}
                {!hasUsername && <ProfileForm />}
              </SignedIn>
            </main>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
