import { Itim } from "next/font/google";
import { ClerkProvider, SignedIn, SignedOut } from "@clerk/nextjs";
import "./globals.css";
import { db } from "@/lib/db";
import { auth, currentUser } from "@clerk/nextjs/server";
import ProfileForm from "./components/ProfileForm";

//Font
const itim = Itim({ subsets: ["latin"], weight: "400" });

//Meta Data
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  //Clerk user id
  const { userId } = auth();

  //Clerk info for user
  const user = await currentUser();

  //SELECT profile for user
  const result = await db.query(
    `SELECT * FROM profiles WHERE clerk_id = '${userId}'`
  );

  //UPDATE profile pic if user exists
  if (userId && result.profile_pic == null)
    await db.query(
      `UPDATE profiles SET profile_pic = '${user.imageUrl}' WHERE clerk_id = '${userId}'`
    );

  //INSERT new user if user doesn't exist
  if (result.rowCount === 0 && userId) {
    await db.query(`INSERT INTO profiles (clerk_id) VALUES ('${userId}')`);
  }

  //If user show page, else show form
  const hasUsername = result.rows[0]?.username !== null ? true : false;
  return (
    <ClerkProvider>
      <html lang="en">
        <link rel="icon" href="letter-m.png" sizes="any" />
        <body className={itim.className}>
          <div className="bg-rose-300 min-h-screen p-3">
            <main>
              <SignedOut>{children}</SignedOut>
              <SignedIn>
                {hasUsername && children}
                {!hasUsername && <ProfileForm />}
              </SignedIn>
            </main>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
